name: Add YouTube Playlist
description: Submit an educational YouTube playlist
title: "[Playlist]: "
labels: ["playlist-submission"]
body:
  - type: input
    id: title
    attributes:
      label: Playlist Title
      description: The full title of the YouTube playlist
      placeholder: "e.g., < Name > by < Creator >"
    validations:
      required: true
      
  - type: input
    id: playlist_link
    attributes:
      label: YouTube Playlist URL
      description: Full link to the YouTube playlist
      placeholder: "https://www.youtube.com/playlist?list=..."
    validations:
      required: true
      
  - type: textarea
    id: summary
    attributes:
      label: Playlist Summary
      description: Provide a detailed description of what this playlist teaches
      placeholder: "Describe the content, teaching style, and what learners can expect from this playlist..."
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the main category for this educational playlist
      options:
        - Frontend Development
        - Backend Development
        - Full Stack Development
        - DevOps
        - Mobile Development
        - Data Structures & Algorithms
        - System Design
        - Cloud Computing
        - Machine Learning/AI
        - Blockchain
        - Other
    validations:
      required: true
      
  # - type: input
  #   id: name
  #   attributes:
  #     label: Your GitHub Username
  #     description: Enter your GitHub username (without @)
  #     placeholder: "e.g., CODEX108"
  #   validations:
  #     required: true
